### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by dograanshu21** [nayanseth/sdn-floodlight-loadbalancing#1]

**Comment by nayanseth** [comment]
The variables have been made global to get access from any method. It is not pretty efficient programming but had some deadlines to clear! Another way this could have been done was passing the dictionary or list as the values stay updated after running the functions.

**Comment by dograanshu21** [comment]
Hi

I am doing a project on LTE and sdn load balancing with mininet topology
and open daylight controller. So can i use the same code for my topology
also. If i need to make some changes can you please let me know where do i
need to make changes as my dead lines are also approaching

Thanks  and regards
Sudhanshu Dogra

**Comment by nayanseth** [comment]
Sorry, I cannot help you with code modification as its your coursework. However you are free to use the code.

**Comment by dograanshu21** [comment]
I understand no problem. Just let me know this much that i need to change
the code right?
