### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by zhouuzhou** [nayanseth/sdn-floodlight-loadbalancing#10]
I can't understand the loadbalancer's code why node < 17.  
17 means what.....      I don't know  where 17 comes from.
The following is the code
def findSwitchRoute():
         for currentPath in nx.all_shortest_paths(G, source=src, target=dst, weight=None):
		for node in currentPath:
			tmp = ""
			if node < 17:
				pathKey = pathKey + "0" + str(hex(node)).split("x",1)[1] + "::"
				tmp = "00:00:00:00:00:00:00:0" + str(hex(node)).split("x",1)[1]
       
expect your reply .thank you .

**Comment by nayanseth** [comment]
That's cause the switch at the top is named 17 (see diagram in README). I forgot to compute top node for any fat tree topology.
