### ISSUE TITLE
Load balancer not working

### ISSUE THREAD

**Issue by ashwin316** [nayanseth/sdn-floodlight-loadbalancing#11]
Hi,
I followed the steps mentioned for the project. I am using the floodlight controller, and everything works fine until the step where we run the loadbalancer.py file. The file runs properly, and I also get the best path in the output. 

However the last 2 steps are not working. I mean in Step 18, we should only see 10.0.0.3 packets, but I see both the packets i.e 10.0.0.3 and 10.0.0.4.

And in the last step, I don't see any packets. I have also properly selected the ports in both the steps. 
Could you please help me?

Thanks

**Comment by nayanseth** [comment]
@Saiyan2208 you will have to debug with the code. I am not maintaining this project anymore. Additionally, you should see what rules are being added to different ports;

Would also suggest you to check the topology. As I have forgotten to compute top node in path calculation. That section of code is static and not dynamic.

I think there is a issue with the Graph as well. Would suggest debugging that as well.
