### ISSUE TITLE
loadbalancer.py is not running properly (TypeError: string indices must be integers)

### ISSUE THREAD

**Issue by shashi19081994** [nayanseth/sdn-floodlight-loadbalancing#12]
Hi nayan, i was using  your sdn load balancing project (i'm using floodlight controller)..while running loadbalancer.py i came across with this "loadbalancer.py is not running properly (TypeError: string indices must be integers)" i have given input as shown i image(which i have attached
![1111](https://user-images.githubusercontent.com/33379716/37460407-28a81500-2871-11e8-8ca3-0580b76ae1c8.png)
) .. in between double quotes..still i'm facing this issue..please help me to resolve this issue.

**Comment by dhabbevijayalaxmi** [comment]
have u solved your issue??

**Comment by shashi19081994** [comment]
No i am unable to resolve the issue...

**Comment by dhabbevijayalaxmi** [comment]
I tried on floodlight v1. 2 version but it gives same error

**Comment by nayanseth** [comment]
Use integer not string
