### ISSUE TITLE
The Destination host can't change.

### ISSUE THREAD

**Issue by zhouuzhou** [nayanseth/sdn-floodlight-loadbalancing#14]
Hi nayanseth：
I try to change H1 H4 H3 to H1 H5 H6 or H1 H7 H8, I found that the program isn't working.  Why can appear such a problem？
![1-5-6](https://user-images.githubusercontent.com/28769835/38906939-f6705396-42eb-11e8-989a-e4cd153b3bd9.png)

**Comment by nayanseth** [comment]
You need to debug it. From the code, I think the graph is not getting populated.
