### ISSUE TITLE
Giving error when trying to rum on fat tree topology

### ISSUE THREAD

**Issue by dograanshu21** [nayanseth/sdn-floodlight-loadbalancing#2]
![error](https://cloud.githubusercontent.com/assets/9971795/20637145/1fbbd416-b3a3-11e6-8382-5f1124b290d0.png)

**Comment by saipoojitha12** [comment]
i am also stuck up with same problem . how to rectify it?

**Comment by nayanseth** [comment]
@saipoojitha12 @dograanshu21 Its a REST API issue. Ensure you are using the same version of SDN controller. If REST output is different. Try to debug that and then run or modify the code.
