### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by hasaniesar** [nayanseth/sdn-floodlight-loadbalancing#20]
@nayanseth Sir kindly look the issue!
\ubuntu@sdnhubvm:~/sdn-loadbalancing[02:12] (master)$ sudo python loadbalancer.y
Enter Host 1
1

Enter Host 2
4

Enter Host 3 (H2's Neighbour)
3
Traceback (most recent call last):
  **File "loadbalancer.py", line 328, in <module>
    getResponse(deviceInfo,"deviceInfo")
  File "loadbalancer.py", line 19, in getResponse
    deviceInformation(jData)
  File "loadbalancer.py", line 35, in deviceInformation
    if(i['ipv4']):
TypeError: string indices must be integers**

**Comment by bigwhite12** [comment]
I have the same question.
Sir,please resolve the issue.

**Comment by hasaniesar** [comment]
Run the load balancer script many times until it is finally executed after 0% packet loss.
