### ISSUE TITLE
Getting error while executing odl.py file

### ISSUE THREAD

**Issue by Dheeraj922** [nayanseth/sdn-floodlight-loadbalancing#3]
Traceback (most recent call last):
  File "/home/dheeraj/PycharmProjects/ODLPython/odl.py", line 244, in <module>
    for path in nx.all_shortest_paths(G, source=int(switch[h2].split(":", 1)[1]), target=int(switch[h1].split(":", 1)[1]), weight=None):
KeyError: '10.0.0.2'

**Comment by nayanseth** [comment]
Did you feed your input as an integer? Do you have a topology created in Mininet?

**Comment by Dheeraj922** [comment]
yes.I provided integers as input and I have also created the custom topology in mininet.The topology is working fine..but it is the odl.py file that is not producing the desired output. I think the array switch in the main portion of the script does not have any values in it. Can you please confirm it?

**Comment by Dheeraj922** [comment]
fixed it. Some modules were not installed correctly on my system..Thanks for your help

**Comment by ponkuu** [comment]
@Dheeraj 

I am trying to run the ODL.py file but facing issues.. can you please tell how did you fix ur script.
