### ISSUE TITLE
Load Balancer.py

### ISSUE THREAD

**Issue by sohaib0001** [nayanseth/sdn-floodlight-loadbalancing#5]
while running the loadbalancer.py script

the error i get is type error: string indices must be integers
what format i must use for entering the host 1 host 2 and neighboring host
Please Guide

**Comment by sohaib0001** [comment]
![capture](https://cloud.githubusercontent.com/assets/28979668/26559825/9854149c-44e4-11e7-83f4-b0ab1f48dbc0.PNG)

**Comment by nayanseth** [comment]
Integer value is correct in input; Ensure everything is up and running i.e. Mininet, Floodlight, etc. Follow all instructions. Its mentioned in Readme

**Comment by sohaib0001** [comment]
Everything is Running and previously I got the said results from wire shark too. but this error is not going away!

**Comment by nayanseth** [comment]
This is a error which is coming when you are performing REST request. So the REST api output is not getting parsed. Check the REST API documentation of floodlight once. Or would suggest print the output, so you get more idea of what is happening.

**Comment by nayanseth** [comment]
See the lines where the error is coming. Every line has a REST url. Try using postmates chrome plugin and finding out whether your controller is giving you output or not

**Comment by sohaib0001** [comment]
line 328 has this http://localhost:8080/wm/device/         and device info

line 19 is device info

line 35 is ipv4

the above said address is not responding on google

**Comment by sohaib0001** [comment]
actually i am getting the output for device info URL! but the error is the same

**Comment by nayanseth** [comment]
That error is a parsing error for JSON data. Manually read the JSON data in the REST url. Search for IPv4. Check the version of Floodlight you are using. Ensure that it is the same as mentioned in the README.
