### ISSUE TITLE
Please Explain

### ISSUE THREAD

**Issue by sohaib0001** [nayanseth/sdn-floodlight-loadbalancing#6]
![capture](https://cloud.githubusercontent.com/assets/28979668/26752090/a5f4f3f2-487a-11e7-9c8e-c0943ff86bb1.PNG)
Please Explain how to remove the default balancer, and how to run the .sh script

Just for the idea to see if i have not made any mistake

**Comment by nayanseth** [comment]
To remove load balancer, you will have to see their documentation. Floodlight imports it as a package. You have to remove that package.

To run shell scripts just type in ./floodlight.sh (in terminal) but before this ensure that you make the script executable i.e. give it executable chmod permissions.
