### ISSUE TITLE
Loadbalancing error traceback with ODL 

### ISSUE THREAD

**Issue by DouwesDekker** [nayanseth/sdn-floodlight-loadbalancing#9]
![218621](https://user-images.githubusercontent.com/33324462/33133168-8312a182-cfce-11e7-96a7-4ee20343a07e.jpg)

**Comment by nayanseth** [comment]
https://github.com/nayanseth/sdn-loadbalancing/issues/3 Check this thread

**Comment by DouwesDekker** [comment]
for odl.py its works properly but for loadbalancer.py i had problem

**Comment by WSDDF** [comment]
what the exactly meaning of the step 1 and step 2(ie Remove the official Floodlight Load Balancer and 
Run the floodlight.sh shell script)
